--- #YAML:1.0
name:               Amazon-SendToKindle
version:            0.1.1
abstract:           Send files to Amazon's personal document service.
author:
    - Nathan Campos <nathanpc@dreamintech.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    MIME::Lite:      3.029
    Net::SMTP::TLS:  0.12
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
